### ISSUE TITLE
Doesn't work on 0.12.x

### ISSUE THREAD

**Issue by molant** [MicrosoftEdge/static-code-scan#83]
This is the error when scanning:
```
_http_outgoing.js:333
    throw new Error('"name" and "value" are required for setHeader().');
          ^
Error: "name" and "value" are required for setHeader().
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at new ClientRequest (_http_client.js:101:14)
    at Object.exports.request (http.js:49:10)
    at Request.start (C:\Projects\modern.IE-static-code-scan\node_modules\request\request.js:583:30)
    at Request.end (C:\Projects\modern.IE-static-code-scan\node_modules\request\request.js:1237:28)
    at C:\Projects\modern.IE-static-code-scan\node_modules\request\request.js:413:12
    at process._tickCallback (node.js:355:11)
```

**Comment by MikeFromSwe** [comment]
Version 0.10.36 as suggested in 
https://github.com/InternetExplorer/modern.IE-static-code-scan/issues/82
worked.

**Comment by Sarkie** [comment]
Can upgrade all the packages but express and its new middleware will need to be looked at.
